# Generated by Django 4.2.7 on 2024-03-07 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_loan_request_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentloanrequestrecord',
            name='borrower',
            field=models.ForeignKey(db_column='borrower', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentloanrequestrecord',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentloanrequestrecord',
            name='status',
            field=models.CharField(default='รอการตรวจสอบ', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentloanrequestrecord',
            name='tuition_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
