# Generated by Django 4.2.7 on 2024-02-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_loan_request_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentloanrequestrecord',
            name='status',
            field=models.CharField(default='รอการตรวจสอบ', max_length=20),
        ),
    ]
