# Generated by Django 4.2.7 on 2024-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_loan_request_record', '0002_alter_studentloanrequestrecord_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentloanrequestrecord',
            name='tuition_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
