# Generated by Django 4.2.7 on 2024-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_loan_request_record', '0003_alter_studentloanrequestrecord_tuition_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentloanrequestrecord',
            name='borrower_name',
            field=models.CharField(default='ชวัลกร รสิตา', max_length=150),
            preserve_default=False,
        ),
    ]
