# Generated by Django 4.2.7 on 2024-03-05 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announced_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
