# Generated by Django 4.2.7 on 2024-02-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerActivitiesHoursRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('hours', models.IntegerField()),
                ('location_name', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField()),
                ('verification', models.FileField(upload_to='private/verify/')),
                ('status', models.CharField(default='รอการยืนยัน', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
