# Generated by Django 4.2.7 on 2024-03-05 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activities_hours_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeractivitieshoursrecord',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
