# Generated by Django 4.2.7 on 2024-03-07 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer_activities_hours_record', '0002_alter_volunteeractivitieshoursrecord_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeractivitieshoursrecord',
            name='borrower',
            field=models.ForeignKey(db_column='borrower', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
