# Generated by Django 4.2.7 on 2024-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_activities_hours_record', '0003_alter_volunteeractivitieshoursrecord_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeractivitieshoursrecord',
            name='borrower_name',
            field=models.CharField(default='ชวัลกร รสิตา', max_length=150),
            preserve_default=False,
        ),
    ]
