# Generated by Django 4.2.7 on 2024-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('choice', models.JSONField()),
                ('question_type', models.CharField(choices=[('MultipleChoice', 'Multiple Choice'), ('Checkbox', 'Checkbox')], max_length=20)),
            ],
        ),
    ]
