# Generated by Django 4.2.7 on 2024-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationquestion',
            name='correct_answer',
            field=models.JSONField(default='exit'),
            preserve_default=False,
        ),
    ]
