# Generated by Django 4.2.7 on 2024-03-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualification_question', '0002_qualificationquestion_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationquestion',
            name='question_type',
        ),
    ]
